#!/bin/sh

ifconfig $INTERFACE 192.168.1.2 192.168.1.3 mtu 1500 netmask 255.255.255.255 #bring up an interface with ip 192.168.1.2. (the ip has to be the same as in you /hosts/myclient0 file). The second ip (192.168.1.3) is the ip of the client on the other side of the vpn tunnel. Usually it is set to be the next available ip.
